# -*- coding: utf-8 -*-
"""model_building.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18fTDrnzZHU8KDbohNv5g19XvDhZ4td_U
"""

# Upgrade/downgrade scikit-learn to match Render
!pip install scikit-learn==1.8.0
!pip install joblib==1.5.3
!pip install pandas==2.3.3
!pip install numpy==2.4.1

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
import joblib

# Load your dataset
from google.colab import files
uploaded = files.upload()  # Upload train.csv
df = pd.read_csv('train.csv')

# Handle missing values
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

# Select features (pick 5)
X = df[['Pclass','Sex','Age','SibSp','Fare']]
y = df['Survived']

# Encode categorical
le = LabelEncoder()
X['Sex'] = le.fit_transform(X['Sex'])

# Scale numerical features
scaler = StandardScaler()
X[['Age','Fare']] = scaler.fit_transform(X[['Age','Fare']])

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Evaluate
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

import joblib
joblib.dump(model, 'titanic_survival_model.pkl')